Repository CntoDev/compositions, pull requests merged in 2020-05, with the labels that each got.

#74 TFN Standard Faction Update v1.14.0
  reference/Task%20Force%20Noctem/composition.sqe
Labels: enhancement

#72 Update v1.14.0
  reference/US%20Army/composition.sqe
Labels: enhancement

#76 Deletion of duplicates
  reference-adaptations/JTAC/composition.sqe
  reference-adaptations/JTAC/header.sqe
  reference-adaptations/Night%20Gear/composition.sqe
  reference-adaptations/Night%20Gear/header.sqe
  reference-adaptations/Silencers/composition.sqe
  reference-adaptations/Silencers/header.sqe
  reference-adaptations/UAV%20OP_1/composition.sqe
  reference-adaptations/UAV%20OP_1/header.sqe
  reference-adaptations/US%20Urban/composition.sqe
  reference-adaptations/US%20Urban/header.sqe
Labels: duplicate

#81 Update composition.sqe
  reference/US%20Army/composition.sqe
Labels: Update
