Repository CntoDev/compositions, pull requests merged in 2021-11, with the labels that each got.

#195 TFN Camo Helmets
  reference-adaptations/TFN%20Camo%20Helmets/composition.sqe
  reference-adaptations/TFN%20Camo%20Helmets/header.sqe
Labels: Enhancement, Standard Faction INDFOR

#200 Add EZFaction module
  reference-adaptations/EZ-Faction/composition.sqe
  reference-adaptations/EZ-Faction/header.sqe
Labels: Enhancement

#203 v3.0.1 - Standard Faction Composition Fixes
  reference/Russian%20Army/composition.sqe
  reference/Russian%20Army/header.sqe
  reference/Task%20Force%20Noctem/composition.sqe
  reference/Task%20Force%20Noctem/header.sqe
  reference/US%20Army/composition.sqe
  reference/US%20Army/header.sqe
Labels: Bug, Standard Faction OPFOR, Standard Faction BLUFOR, Standard Faction INDFOR
